# weekly_update.yml
# -----------------
# Triggers every Sunday at 15:40 Bangkok time (08:40 UTC).
# Updates the horoscope index page: date range, Yoast title,
# and chart image. Runs 7 minutes after publish_horoscopes.yml
# to ensure sign pages are live before the index links to them.

name: Weekly Horoscope Index Update

on:
  schedule:
    - cron: '40 8 * * 0'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      TZ: UTC
      WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: pip install requests
      - name: Run updater
        run: python update_index.py
